original:
  valid_constraints: ['work', 'contention']
  solver_options:
    MIPGapAbs: 0
    MIPGap: 0
    OutputFlag: 1
    LogToConsole: 1
    TimeLimit: 600
benders:
  max_iters: 10000
  max_time: 600
  mip_gap_obj: 0
  mip_gap_cost: 0
  solver_options_master:
    MIPGapAbs: 0
    MIPGap: 0
    OutputFlag: 0
    LogToConsole: 0
    TimeLimit: 600
  solver_options_subproblem:
    MIPGapAbs: 0
    MIPGap: 0
    OutputFlag: 0
    LogToConsole: 0
    TimeLimit: 600
original_scip:
  limits/time: 600
  display/verblevel: 0
fix_work:
  mip_gap_obj: 0.01
  n_start_info: null
  max_iters: 1000
  max_time: 600
  start_period: 20
  step_period: 6
  valid_constraints: ['max_obj', 'work', 'contention']
  solver_options:
    MIPGapAbs: 0
    MIPGap: 0
    OutputFlag: 0
    LogToConsole: 0
    TimeLimit: 600
benders_scip:
  limits/time: 600
  display/verblevel: 0
gcg_scip:
  limits/time: 600
  display/verblevel: 0